### ISSUE TITLE
On a completely empty database the first launch crashes in migration#20

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#426]
```
{"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 20","time":{"$date":1522479868646},"level":"info"}

/4minitz_bin/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at Function.MongoError.create (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    at /4minitz_bin/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
    at /4minitz_bin/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
``` 

Seems we forgot to iterate in `function saveTopics(topics)` and `function saveMinutes(minutes)`

**Comment by bmgante** [comment]
Hi @derwok 
Sorry to ask for something you posted years ago... but i am having this error in an initial setup in eks using both the stable and unstable docker images. Can you help on this?

```
k logs -f fourminitz-fourminitz-85b6ddcd77-s5mfd
Copying 4minitz_settings.json to your local host directory - once!
DONE.
You may edit the settings file locally on your host.
Then restart this docker container.

Checking for MongoDB
MongoDB is up and running, starting 4Minitz...

***********************************
*-- Welcome to 4Minitz in Docker--*
*                                 *
* IF                              *
*   you launched the container    *
*   with the -p 3100:3333 option  *
* THEN                            *
*   You can open 4Minitz on your  *
*   host browser via:             *
*   http://localhost:3100         *
***********************************


/4minitz_bin/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:867:14)
```
