### ISSUE TITLE
Malformed HELO argument - cannot send mail.

### ISSUE THREAD

**Issue by BigBlockStudios** [4minitz/4minitz#566]
Hi I have 4minitz docker installation in an amazon lightsail container (centos 7)  but it is not able to send mail.  It can connect, but I keep getting a malformed HELO argument. 

`WebApp current working directory:/4minitz_bin/bundle/programs/server
Exception while invoking method 'forgotPassword' Error: Can't send mail - all recipients were rejected: 550 5.7.0 HELO argument [[127.0.0.1]] is malformed. See http://spamauditor.org/best-practices/valid-helo-identifier/ for more information. Protection provided by MagicSpam 2.0.18-1 http://www.magicspam.com    
at SMTPConnection._formatError (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)    
at SMTPConnection._actionRCPT (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1338:28)    
at SMTPConnection._responseActions.push.str (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1293:30)    
at SMTPConnection._processResponse (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)    
at SMTPConnection._onData (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)    
at TLSSocket._socket.on.chunk (/4minitz_bin/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:658:51)    
at emitOne (events.js:116:13)    
at TLSSocket.emit (events.js:211:7)    
at addChunk (_stream_readable.js:263:12)    
at readableAddChunk (_stream_readable.js:250:11)    
at TLSSocket.Readable.push (_stream_readable.js:208:10)    
at TLSWrap.onread (net.js:594:20)`

and the receiving server... 

`Feb 27 12:51:33 myzh-mr7n postfix/smtpd[23470]: NOQUEUE: milter-reject: RCPT from ec2-3-97-34-226.ca-central-1.compute.amazonaws.com[3.97.34.226]: 550 5.7.0 HELO argument [[127.0.0.1]] is malformed. See http://spamauditor.org/best-practices/valid-helo-identifier/ for more information. Protection provided by MagicSpam 2.0.18-1 http://www.magicspam.com; from=<no-reply@example.com> to=<sean@kimballarms.ca> proto=ESMTP helo=<[127.0.0.1]>
`

I don't see any options to correct this in the json file, nor have any idea where the 'no-reply@example.com' is coming from.

how to fix??

**Comment by undefined90** [comment]
Did you already tried another Mail Server?

**Comment by viegelinsch** [comment]
Please provide the values for the following two variables from your settings.json:

- `defaultEMailSenderAddress`
- `fallbackEMailSenderAddress`

**Comment by dimst23** [comment]
I have the same error _(I am using docker)_. Both of the variables are set as they should in the `settings` JSON file. I have also tested the mail server and can successfully send emails. When I try to do password recovery I get a rejection since it tries to send as `no-reply@example.com` and not as one of the `defaultEMailSenderAddress` or `fallbackEMailSenderAddress`.
